# Generated by Django 4.1.1 on 2022-09-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namesmodel',
            name='mydocument',
            field=models.FileField(blank=True, null=True, upload_to='myfiles/'),
        ),
        migrations.AddField(
            model_name='namesmodel',
            name='myimage',
            field=models.ImageField(blank=True, null=True, upload_to='logistics/images/vehicles/%Y/'),
        ),
    ]
