# Generated by Django 4.1.1 on 2022-09-30 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllifmaalCustomersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('Somalia', 'Somalia'), ('Somaliland', 'Somaliland'), ('Kenya', 'Kenya'), ('Other', 'Other')], max_length=30)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalExpensesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=25, null=True)),
                ('amount', models.FloatField(blank=True, default=0, max_length=20, null=True)),
                ('comments', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalTasksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete')], default='incomplete', max_length=10)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('taskDay', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalInvoicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_due_Date', models.DateField(blank=True, null=True)),
                ('invoice_terms', models.CharField(choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('15 days', '15 days'), ('30 days', '30 days')], default='Cash', max_length=20)),
                ('invoice_status', models.CharField(choices=[('Paid', 'Paid'), ('Current', 'Current'), ('Overdue', 'Overdue')], default='Current', max_length=20)),
                ('invoice_currency', models.CharField(choices=[('KES', 'KES'), ('$', 'USD'), ('£', 'EURO')], default='$', max_length=20)),
                ('invoice_comments', models.CharField(blank=True, default='invoice', max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('posting_inv_status', models.CharField(blank=True, choices=[('waiting', 'waiting'), ('posted', 'posted')], default='waiting', max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allifrelatcustinvoice', to='allifmaalapp.allifmaalcustomersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalInvoiceItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('allifinvitemconnector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allifinvitemrelated', to='allifmaalapp.allifmaalinvoicesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalCustomerPaymentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('comments', models.CharField(blank=True, default='comment', max_length=15, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allifcustpaymentreltedname', to='allifmaalapp.allifmaalcustomersmodel')),
            ],
        ),
    ]
