# Generated by Django 3.2.8 on 2022-09-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllifmaalInvoicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_due_Date', models.DateField(blank=True, null=True)),
                ('invoice_terms', models.CharField(choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('15 days', '15 days'), ('30 days', '30 days')], default='Cash', max_length=20)),
                ('invoice_status', models.CharField(choices=[('Paid', 'Paid'), ('Current', 'Current'), ('Overdue', 'Overdue')], default='Current', max_length=20)),
                ('invoice_currency', models.CharField(choices=[('KES', 'KES'), ('$', 'USD'), ('£', 'EURO')], default='$', max_length=20)),
                ('invoice_comments', models.CharField(blank=True, default='invoice', max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('posting_inv_status', models.CharField(blank=True, choices=[('waiting', 'waiting'), ('posted', 'posted')], default='waiting', max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allifrelatcustinvoice', to='allifmaalapp.allifmaalcustomersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalInvoiceItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('allifinvitemconnector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allifinvitemrelated', to='allifmaalapp.allifmaalinvoicesmodel')),
            ],
        ),
    ]
