# Generated by Django 3.2.8 on 2022-09-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalapp', '0003_allifmaalcustomerpaymentsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllifmaalExpensesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=25, null=True)),
                ('amount', models.FloatField(blank=True, default=0, max_length=20, null=True)),
                ('comments', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
