# Generated by Django 3.2.8 on 2022-09-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalapp', '0004_allifmaalexpensesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllifmaalTasksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete')], default='incomplete', max_length=10)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('taskDay', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10)),
            ],
        ),
    ]
